### ISSUE TITLE
Fathom returns wrong result in some positions.

### ISSUE THREAD

**Issue by basil00** [basil00/Fathom#10]
E.g.

```
5k2/8/5K2/8/6p1/8/7P/4B3 w - - 0 1
```

Fathom plays `h4` (a drawing move).  This issue was discovered by Marco Costalba and reported here: http://talkchess.com/forum/viewtopic.php?p=673269#673269
(This is probably a bug in the original syzygy probing code, not specific to Fathom's version).

If I understand the issue correctly, it seems this can only turn a win into a draw (never a win or draw into a loss).

**Comment by niklasf** [comment]
Just saw the commit in Stockfish official-stockfish/Stockfish@6e2ca97d93812b2 and came here to report it. Only to see it already fixed. Very nice, much appreciated! :+1:
