### ISSUE TITLE
Invalid PGN generated

### ISSUE THREAD

**Issue by brtzsnr** [basil00/Fathom#21]
For the following endgame the rooks are captured early on and the game continues with only kings.

% fathom.linux --path ~/syzygy/ "8/5k1r/8/8/6K1/8/8/R7 w - - 0 1"
[Event ""]
[Site ""]
[Date "??"]
[Round "-"]
[White "Syzygy"]
[Black "Syzygy"]
[Result "1/2-1/2"]
[FEN "8/5k1r/8/8/6K1/8/8/R7 w - - 0 1"]
[WDL "Draw"]
[DTZ "0"]
[WinningMoves ""]
[DrawingMoves "Kf3, Kg3, Kf4, Kf5, Kg5, Rb1, Rc1, Rd1, Re1, Rf1, Ra2, Ra3, Ra4, Ra5, Ra6, Ra7, Ra8"]
[LosingMoves "Rg1, Rh1"]

1. Ra7+ Kg6 2. Rxh7 Kxh7 3. Kf3 Kg6 4. Ke2 Kf5 5. Kd1 Ke4 6. Kc1 Kd3 7. Kb1 Kd2 8. Ka1 Kc1 9. Ka2 Kd1 10. Ka1 Kc1 11. Ka2 Kd1 12. Ka1 Kc1 13. Ka2 Kd1 14. Ka1 Kc1 15. Ka2 Kd1 16. Ka1 Kc1 17. Ka2 Kd1 18. Ka1 Kc1 19. Ka2 Kd1 20. Ka1 Kc1 21. Ka2 Kd1 22. Ka1 Kc1 23. Ka2 Kd1 24. Ka1 Kc1 25. Ka2 Kd1 26. Ka1 Kc1 27. Ka2 Kd1 28. Ka1 Kc1 29. Ka2 Kd1 30. Ka1 Kc1 31. Ka2 Kd1 32. Ka1 Kc1 33. Ka2 Kd1 34. Ka1 Kc1 35. Ka2 Kd1 36. Ka1 Kc1 37. Ka2 Kd1 38. Ka1 Kc1 39. Ka2 Kd1 40. Ka1 Kc1 41. Ka2 Kd1 42. Ka1 Kc1 43. Ka2 Kd1 44. Ka1 Kc1 45. Ka2 Kd1 46. Ka1 Kc1 47. Ka2 Kd1 48. Ka1 Kc1 49. Ka2 Kd1 50. Ka1 Kc1 51. Ka2 Kd1 52. Ka1 Kc1 1/2-1/2

**Comment by basil00** [comment]
What's the problem with the PGN?

Note that some rules such as draw-by-repetition are ignored.  The PGN format is just a convenient way to represent the tablebase moves.

**Comment by brtzsnr** [comment]
In understand that but after 2... Kxh7 there are only kings on the board which is already a theoretical draw so the last 50 full moves should not happen at all.

**Comment by basil00** [comment]
As mentioned, it does not implement all drawing rules.
