### ISSUE TITLE
tb_init

### ISSUE THREAD

**Issue by jdart1** [basil00/Fathom#3]
I suggest renaming the "tb_init" function to "syzygy_tb_init". "tb_init" conflicts with the name of the function used to initialize Gaviota tablebases (see https://sites.google.com/site/gaviotachessengine/Home/endgame-tablebases-1). If you want to support both there is no easy way to do that.

Also IMO it would be cleaner if the init function returned the man count of the table bases found rather than setting it in a global variable.

**Comment by basil00** [comment]
That is a problem.  Perhaps it would be better to prefix everything with `syzygy_` in place of `tb_`?

**Comment by basil00** [comment]
I think it is easiest to replace `tb_init` with `tb_init_impl`, and have an inlined wrapper `tb_init` function in the header file.  The wrapper can be renamed via a macro hack if desired, e.g.

```
#define tb_init syzygy_tb_init
#include <tbprobe.h>
#undef tb_init
```

Replacing the prefix everywhere is too messy at this stage.

> Also IMO it would be cleaner if the init function returned the man count of the table bases found rather than setting it in a global variable.

Perhaps; but this is something I just copied from the original probe code.
