### ISSUE TITLE
Compiling on Linux (arm)

### ISSUE THREAD

**Issue by djdekker** [basil00/Fathom#9]
tbprobe.c calls x86intrin.h, but this prohibits compiling on Linux arm devices like Raspberry Pi. Is there a way around this?

**Comment by basil00** [comment]
Basically you'd need to port Fathom to ARM.  Either by replacing the x86-specific stuff with ARM equivalents (if they exist) and/or replacing with generic code.  If you do this then please submit a pull request.

**Comment by djdekker** [comment]
Thanks, I have no time to investigate x86 equivalents. I'll leave out Syzygy functionality on Raspberry Pi.
